name: Graph Wizard
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  graph-builder:
    runs-on: ubuntu-latest
    steps:
      - name: Update
        run: sudo apt update >> wizard.log
      - name: Python Version
        run: python --version >> wizard.log
      - name: Display Logs
        run: cat wizard.log
